CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE DOMAIN postal_code AS TEXT DEFAULT '75000';
    CHECK ( 
    VALUE ~ '^\d{5}$'
    OR VALUE ~ '^\d{5}-\d{4}$'
    );

  create domain postal_code as text default '75000' check (value ~ '^\d{5}$' or value ~ '^\d{5}-\d{4}$');

    CREATE TABLE IF NOT EXISTS events (
      id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW(),
      picto TEXT,
      title VARCHAR(255) NOT NULL,
      description TEXT,
      datetime TIMESTAMP,
      location TEXT NOT NULL,
      adressNum INT,
      adressRoad TEXT NOT NULL,
      city VARCHAR(255) NOT NULL,
      zipCode postal_code NOT NULL,
      stocks INT NOT NULL,
      sells INT,
      price INT NOT NULL
    );

INSERT INTO "public"."events" 
        ( 
            "picto", 
            "title", 
            "description", 
            "datetime", 
            "location", 
            "adressnum", 
            "adressroad", 
            "city", 
            "zipcode", 
            "stocks", 
            "sells", 
            "price"
        ) 
VALUES (
            'archery', 
            'Archery', 
            'Athletes shoot arrows at a target from a set distance.', 
            '2024-08-16 14:00:00', 
            'Les Invalides', 
            '2', 
            'Place Vauban', 
            'Paris', 
            '75007', 
            '4000', 
            '0', 
            '45'
        ),
        (
            'artistic-gymnastics', 
            'Artistic Gymnastics', 
            'Athletes perform routines on apparatus with strength and grace.', 
            '2024-08-03 09:30:00', 
            'Arena Bercy', 
            '8', 
            'Boulevard de Bercy', 
            'Paris', 
            '75012', 
            '17000', 
            '0', 
            '60'
        ),
        (
            'artistic-swimming', 
            'Artistic Swimming', 
            'Synchronized water dance with strength and flexibility.', 
            '2024-08-06 10:00:00', 
            'Paris La Défense Arena', 
            '99', 
            'Jardin de l\'Arche', 
            'Nanterre', 
            '92000', 
            '2500', 
            '0', 
            '34'
        ), 
        (
            'atheltics', 
            'Athletics', 
            'Track and field events like sprints, jumps, and throws.', 
            '2024-08-12 09:00:00', 
            'Stade de France', 
            null, 
            'Avenue du Stade de France', 
            'Saint-Denis', 
            '93200', 
            '81000', 
            '0', 
            '55'
        ), 
        (
            'badminton', 
            'Badminton', 
            'Racquet sport where players hit a shuttlecock over a net.', 
            '2024-08-11 09:30:00', 
            'Arena Porte de la Chapelle', 
            '56', 
            'Boulevard Ney', 
            'Paris', 
            '75018', 
            '10000', 
            '0', 
            '24'
        ), 
        (
            'basketball', 
            'Basketball', 
            'Five-a-side team game of shooting hoops on a full court.', 
            '2024-08-03 18:30:00', 
            'Arena Bercy', 
            '8', 
            'Boulevard de Bercy', 
            'Paris', 
            '75012', 
            '17000', 
            '0', 
            '80'
        ), 
        (
            'beach-volleyball', 
            'Beach Volleyball', 
            'Two-player teams compete on sand courts.', 
            '2024-08-10 14:00:00', 
            'Stade Tour Eiffel (Emile Anthoine)', 
            '2', 
            'Avenue de Suffren', 
            'Paris', 
            '75007', 
            '25000', 
            '0', 
            '25'
        ), 
        (
            'boxing', 
            'Boxing', 
            'Combat sport where opponents try to land punches.', 
            '2024-08-11 18:00:00', 
            'Stade Roland Garros', 
            '2', 
            'Avenue Gordon Benett', 
            'Paris', 
            '75016', 
            '5000', 
            '0', 
            '35'
        ), 
        (
            'breaking', 
            'breaking', 
            'Dance sport combining style, strength, and acrobatics.', 
            '2024-07-30 14:00:00', 
            'Place de la Concorde', 
            null, 
            'Place de la Concorde', 
            'Paris', 
            '75000', 
            '2000', 
            '0', 
            '35'
        ), 
        (
            'canoe-slalom', 
            'Canoe Slalom', 
            'Timed race through a whitewater course in a canoe or kayak. ', 
            '2024-08-02 10:00:00', 
            'Base nautique de Vaires-sur-Marne', 
            null, 
            'Route de Torcy', 
            'Vaires-sur-Marne', 
            '77360', 
            '4000', 
            '0', 
            '35'
        ), 
        (
            'canoe-sprint', 
            'Canoe Sprint', 
            'Flatwater racing in canoes or kayaks over short distances.', 
            '2024-08-03 10:00:00', 
            'Base nautique de Vaires-sur-Marne', 
            null, 
            'Route de Torcy', 
            'Vaires-sur-Marne', 
            '77360', 
            '4000', 
            '0', 
            '35'
        ), 
        (
            'cycling-bmx-free', 
            'Cycling BMX Freestyle', 
            'Riders perform tricks and stunts on a BMX bike.', 
            '2024-08-05 10:00:00', 
            'Place de la Concorde', 
            null, 
            'Place de la Concorde', 
            'Paris', 
            '75000', 
            '2000', 
            '0', 
            '35'
        ), 
        (
            'cycling-bmx-race', 
            'Cycling BMX Racing', 
            'Fast-paced dirt track races on BMX bikes.', 
            '2024-08-05 14:00:00', 
            'Place de la Concorde', 
            null, 
            'Place de la Concorde', 
            'Paris', 
            '75000', 
            '2000', 
            '0', 
            '35'
        ),
        (
            'cycling-mount-bike', 
            'Cycling Mountain Bike', 
            'Off-road racing over rugged terrain.', 
            '2024-08-08 00:00:00', 
            'Pont d\'Iéna - Trocadéro', 
            null, 
            'Pont d\'Iéna - Trocadéro', 
            'Paris', 
            '75116', 
            '5000', 
            '0', 
            '35'
        ), 
        (
            'cycling-road', 
            'Cycling Road', 
            'Long-distance races on paved roads.', 
            '2024-08-01 14:00:00', 
            'Pont Alexandre III', 
            null, 
            'Pont Alexandre III', 
            'Paris', 
            '75008', 
            '2000', 
            '0', 
            '35'
        ), 
        (
            'cycling-track', 
            'Cycling Track', 
            'High-speed racing on an indoor velodrome.', 
            '2024-08-03 10:00:00', 
            'Vélodrome National', 
            '1', 
            'Rue Laurent Fignon, Place de la Paix Celeste', 
            'Montigny-le-Bretonneux', 
            '78180', 
            '2500', 
            '0', 
            '35'
        ), 
        (
            'diving', 
            'Diving', 
            'Athletes perform acrobatic dives from platforms or springboards.', 
            '2024-08-12 16:30:00', 
            'Centre Aquatique Olympique', 
            '345', 
            'Avenue du Président Wilson', 
            'Saint-Denis', 
            '93200', 
            '5000', 
            '0', 
            '35'
        ),
        (
            'equestrian', 
            'Equestrian', 
            'Horse riding competitions in jumping, dressage, and eventing.', 
            '2024-08-05 09:30:00', 
            'Château de Versailles', 
            null, 
            'Place d\'Armes', 
            'Versailles', 
            '78000', 
            '3000', 
            '0', 
            '35'
        ), 
        (
            'fencing', 
            'Fencing', 
            'Duel with swords where athletes score touches.', 
            '2024-08-18 10:00:00', 
            'Grand Palais', 
            '1', 
            'Avenue Wiston Churchill', 
            'Paris', 
            '75008', 
            '15000', 
            '0', 
            '35'
        ), 
        (
            'football', 
            'Football', 
            'Teams aim to score by getting the ball into the opponent’s goal.', 
            '2024-07-21 15:00:00', 
            'Stade Vélodrome', 
            '3', 
            'Boulevard Michelet', 
            'Marseille', 
            '13008', 
            '50000', 
            '0', 
            '35'
        ),
        (
            'golf', 
            'Golf', 
            'Players aim to hit balls into holes with as few strokes as possible.', 
            '2024-07-27 10:00:00', 
            'Château de Versailles', 
            null, 
            'Place d\'Armes', 
            'Versailles', 
            '78000', 
            '3000', 
            '0', 
            '35'
        ), 
        (
            'handball', 
            'Handball', 
            'Fast team sport where players throw a ball to score goals.', 
            '2024-07-30 15:00:00', 
            'Arena Paris Sud (Palais des Expositions - Porte de Versailles)', 
            '1', 
            'Place de la Porte de Versaille', 
            'Paris', 
            '75015', 
            '2000', 
            '0', 
            '35'
        ), 
        (
            'hockey', 
            'Hockey', 
            'Teams use sticks to hit a ball into the goal on a turf field.', 
            '2024-07-30 17:30:00', 
            'Arena Champ-de-Mars (Grand Palais éphémère)', 
            '2', 
            'Place Joffre', 
            'Paris', 
            '72007', 
            '1500', 
            '0', 
            '35'
        ), 
        (
            'judo', 
            'Judo', 
            'Martial art focused on throws and submissions.', 
            '2024-07-28 09:30:00', 
            'Arena Champ-de-Mars (Grand Palais éphémère)', 
            '2', 
            'Place Joffre', 
            'Paris', 
            '72007', 
            '1500', 
            '0', 
            '35'
        ), 
        (
            'marathon-swimming', 
            'Marathon Swimming', 
            'Long-distance open water swim over 10 kilometers.', 
            '2024-07-31 10:00:00', 
            'Pont Alexandre III', 
            null, 
            'Pont Alexandre III', 
            'Paris', 
            '75008', 
            '1500', 
            '0', 
            '35'
        ), 
        (
            'modern-pentathlon', 
            'Modern Pentathlon', 
            'Five-discipline event: fencing, swimming, equestrian, shooting, and running.', 
            '2024-08-01 08:00:00', 
            'Pont Alexandre III', 
            null, 
            'Pont Alexandre III', 
            'Paris', 
            '75008', 
            '2000', 
            '0', 
            '35'
        ), 
        (
            'rhytmic-gymnastics', 
            'Rhytmic Gymnastics', 
            'Gymnasts perform with ribbons, hoops, balls, or clubs.', 
            '2024-08-09 09:30:00', 
            'Arena Porte de la Chapelle', 
            '56', 
            'Boulevard Ney', 
            'Paris', 
            '75018', 
            '10000', 
            '0', 
            '35'    
        ), 
        (
            'rowing', 
            'Rowing', 
            'Teams or individuals race boats using oars.', 
            '2024-08-03 09:30:00', 
            'Base nautique de Vaires-sur-Marne', 
            null, 
            'Route de Torcy', 
            'Paris', 
            '77360', 
            '4000', 
            '0', 
            '35'
        ), 
        (
            'rugby-sevens', 
            'Rugby Sevens', 
            'Fast-paced 7-player rugby played in two short halves.', 
            '2024-07-28 18:00:00', 
            'Stade de France', 
            null, 
            'Avenue du Stade de France', 
            'Saint-Denis', 
            '93200', 
            '81000', 
            '0', 
            '35'
        ), 
        (
            'sailing', 
            'Sailing', 
            'Races where athletes navigate boats using wind power.', 
            '2024-08-17 08:30:00', 
            'Stade Roland Garros', 
            null, 
            'Marina', 
            'Marseille', 
            '13000', 
            '25000', 
            '0', 
            '35'
        ), 
        (
            'shooting', 
            'Shooting', 
            'Precision sport with rifles or pistols aiming at targets.', 
            '2024-08-03 14:00:00', 
            'Place de la Concorde', 
            null, 
            'Place de la Concorde', 
            'Paris', 
            '75000', 
            '2000', 
            '0', 
            '35'
        ), 
        (
            'skateboarding', 
            'Skateboarding', 
            'Riders perform tricks on ramps and rails.', 
            '2024-08-01 10:00:00', 
            'Place de la Concorde', 
            null, 
            'Place de la Concorde', 
            'Paris', 
            '75000', 
            '2000', 
            '0', 
            '35'
        ), 
        (
            'sport-climbing', 
            'Sport Climbing', 
            'Athletes climb walls using speed, technique, and strength.', 
            '2024-08-05 10:00:00', 
            'Grand Palais', 
            '1', 
            'Avenue Wiston Churchill', 
            'Paris', 
            '75008', 
            '15000', 
            '0', 
            '35'
        ),
        (
            'surfing', 
            'Surfing', 
            'Riders catch and perform maneuvers on ocean waves.', 
            '2024-08-09 00:00:00', 
            'Stade Roland Garros', 
            null, 
            'Plage de Teahupo\''o\'', 
            'Tahiti', 
            '98723', 
            '10000', 
            '0', 
            '35'
        ), 
        (
            'swimming', 
            'Swimming', 
            'Races over various distances and strokes in a pool.', 
            '2024-08-13 10:00:00', 
            'Centre Aquatique Olympique', 
            '345', 
            'Avenue du Président Wilson', 
            'Saint-Denis', 
            '93200', 
            '5000', 
            '0', 
            '35'
        ), 
        (
            'table-tennis', 
            'Table Tennis', 
            'Fast-paced ping pong with quick reflexes and spin shots.', 
            '2024-07-26 15:00:00', 
            'Arena Paris Sud (Palais des Expositions - Porte de Versailles)', 
            '1', 
            'Place de la Porte de Versaille', 
            'Paris', 
            '75015', 
            '2000', 
            '0', 
            '35'
        ), 
        (
            'taekwondo', 
            'Taekwondo', 
            'Korean martial art with fast kicks and footwork.', 
            '2024-08-21 10:00:00', 
            'Grand Palais', 
            '1', 
            'Avenue Wiston Churchill', 
            'Paris', 
            '75008', 
            '15000', 
            '0', 
            '35'
        ), 
        (
            'tennis', 
            'Tennis', 
            'Players use racquets to hit a ball over a net into the opponent\'s court.', 
            '2024-08-11 15:00:00', 
            'Stade Roland Garros', 
            '2', 
            'Avenue Gordon Benett', 
            'Paris', 
            '75016', 
            '5000', 
            '0', 
            '35'
        ), 
        (
            'trampoline-gymnastics', 
            'Trampoline Gymnastics', 
            'Athletes perform aerial flips and twists on a trampoline.', 
            '2024-08-03 15:30:00', 
            'Arena Bercy', 
            '8', 
            'Boulevard de Bercy', 
            'Paris', 
            '75012', 
            '17000', 
            '0', 
            '35'
        ), 
        (
            'triathlon', 
            'Triathlon', 
            'Multisport race combining swimming, cycling, and running.', 
            '2024-07-28 10:00:00', 
            'Pont Alexandre III', 
            null, 
            'Pont Alexandre III', 
            'Paris', 
            '75008', 
            '1500', 
            '0', 
            '35'
        ), 
        (
            'volleyball', 
            'Volleyball', 
            'Teams hit a ball over a net to ground it on the other side.', 
            '2024-07-26 16:00:00', 
            'Arena Paris Sud (Palais des Expositions - Porte de Versailles)', 
            '1', 
            'Place de la Porte de Versaille', 
            'Paris', 
            '75015', 
            '2000', 
            '0', 
            '35'
        ),
        (
            'water-polo', 
            'Water Polo', 
            'Aquatic team sport of goals and ball passing.', 
            '2024-08-04 15:00:00', 
            'Paris La Défense Arena', 
            '99', 
            'Jardin de l\'Arche', 
            'Nanterre', 
            '92000', 
            '2500', 
            '0', 
            '35'
        ), 
        (
            'weightlifting', 
            'Weightlifting', 
            'Lifting maximum weights in two overhead lifts.', 
            '2024-07-26 10:00:00', 
            'Arena Paris Sud (Palais des Expositions - Porte de Versailles)', 
            '1', 
            'Place de la Porte de Versaille', 
            'Paris', 
            '75015', 
            '2000', 
            '0', 
            '35'
        ), 
        (
            'wrestling', 
            'Wrestling', 
            'Combat sport with grappling and pinning techniques.', 
            '2024-08-15 09:30:00', 
            'Arena Champ-de-Mars (Grand Palais éphémère)', 
            '2', 
            'Place Joffre', 
            'Paris', 
            '75007', 
            '1500', 
            '0', 
            '35'
        ), 
        (
            'xBasketBall', 
            '3x3 Basketball', 
            'Fast-paced 3-on-3 basketball played on a half court.', 
            '2024-07-28 14:00:00', 
            'Place de la Concorde', 
            null, 
            'Place de la Concorde', 
            'Paris', 
            '75000', 
            '2000', 
            '0', 
            '50'
        );

alter table "public"."events" enable row level security;

create policy "Enable read access for visitors."
on "public"."events" for select
to anon, authenticated
using ( true );