// This file is the starter of data for the app.
// Variable are used in seed/route.ts to insert first data in database

const users = [
    {
        name: 'Admin_Paris2024',
        surname: 'Olympics',
        email: 'orga-paris2024@olympics.fr',
        phone:'',
        password: 'JOParis2024_Admin',
        nationality: 'France',
        admin: true
    },
];

// * => Notes : 
// * Prices of one e-ticket are between 24 and 950 euros (€) ATI (All Taxes Included)
// * Dates included events : 26/07/2024 and 11/08/2024

const events = [
    {
        picto:'3x3BasketBall',
        title:'3x3 Basketball',
        description: 'Meeting of three players against three players on a midground with one basket. Match of ten minutes playing or 21 pts for a team to win.',
        datetime: '2024-07-28 14:00:00',
        location: 'Place de la Concorde',
        adressNum: null,
        adressRoad: 'Place de la Concorde',
        city: 'Paris',
        zipCode: 75000,
        stocks: 2000,
        sells: 0,
        price: 50
    },
    {
        picto: 'archery',
        title: 'Archery',
        description: 'Competition of archery where coutries are represent by team of one shot players. They must shoot in a target.',
        datetime: '2024-08-16 14:00:00',
        location: 'Les Invalides',
        adressNum: 2,
        adressRoad: 'Place Vauban',
        city: 'Paris',
        zipCode: 75007,
        stocks: 4000,
        sells: 0,
        price: 45
    },
    {
        picto: 'artistic-gymnastics',
        title: 'Artistic Gymnastics',
        description: 'Performance of gymnasts where spectacular and artistics choregrahies meet physical gym\'s movements.',
        datetime: '2024-08-03 09:30:00',
        location: 'Arena Bercy',
        adressNum: 8,
        adressRoad: 'Boulevard de Bercy',
        city: 'Paris',
        zipCode: 75012,
        stocks: 17000,
        sells: 0,
        price: 60
    },
    {
        picto: 'artistic-swimming',
        title: 'Artistic Swimming',
        description: '',
        datetime: '2024-08-06 10:00:00',
        location: 'Paris La Défense Arena',
        adressNum: 99,
        adressRoad: 'Jardin de l\'Arche',
        city: 'Nanterre',
        zipCode: 92000,
        stocks: 2500,
        sells: 0,
        price: 34
    },
    {
        picto: 'atheltics',
        title: 'Athletics',
        description: '',
        datetime: '2024-08-12 09:00:00',
        location: 'Stade de France',
        adressNum: null,
        adressRoad: 'Avenue du Stade de France',
        city: 'Saint-Denis',
        zipCode: 93200,
        stocks: 81000,
        sells: 0,
        price: 55
    },
    {
        picto: 'badminton',
        title: 'Badminton',
        description: '',
        datetime: '2024-08-11 09:30:00',
        location: 'Arena Porte de la Chapelle',
        adressNum: 56,
        adressRoad: 'Boulevard Ney',
        city: 'Paris',
        zipCode: 75018,
        stocks: 10000,
        sells: 0,
        price: 24
    },
    {
        picto: 'basketball',
        title: 'Basketball',
        description: '',
        datetime: '2024-08-03 18:30:00',
        location: 'Arena Bercy',
        adressNum: 8,
        adressRoad: 'Boulevard de Bercy',
        city: 'Paris',
        zipCode: 75012,
        stocks: 17000,
        sells: 0,
        price: 80
    },
    {
        picto: 'beach-volleyball',
        title: 'Beach Volleyball',
        description: '',
        datetime: '2024-08-10 14:00:00',
        location: 'Stade Tour Eiffel (Emile Anthoine)',
        adressNum: 2,
        adressRoad: 'Avenue de Suffren',
        city: 'Paris',
        zipCode: 75007,
        stocks: 25000,
        sells: 0,
        price: 25
    },
    {
        picto: 'boxing',
        title: 'Boxing',
        description: '',
        datetime: '2024-08-11 18:00:00',
        location: 'Stade Roland Garros',
        adressNum: 2,
        adressRoad: 'Avenue Gordon Benett',
        city: 'Paris',
        zipCode: 75016,
        stocks: 5000,
        sells: 0,
        price: 35
    },
    {
        picto: 'breaking',
        title: 'breaking',
        description: '',
        datetime: '2024-07-30 14:00:00',
        location: 'Place de la Concorde',
        adressNum: null,
        adressRoad: 'Place de la Concorde',
        city: 'Paris',
        zipCode: 75000,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'canoe-slalom',
        title: 'Canoe Slalom',
        description: '',
        datetime: '2024-08-02 10:00:00',
        location: 'Base nautique de Vaires-sur-Marne',
        adressNum: null,
        adressRoad: 'Route de Torcy',
        city: 'Vaires-sur-Marne',
        zipCode: 77360,
        stocks: 4000,
        sells: 0,
        price: 35
    },
    {
        picto: 'canoe-sprint',
        title: 'Canoe Sprint',
        description: '',
        datetime: '2024-08-03 10:00:00',
        location: 'Base nautique de Vaires-sur-Marne',
        adressNum: null,
        adressRoad: 'Route de Torcy',
        city: 'Vaires-sur-Marne',
        zipCode: 77360,
        stocks: 4000,
        sells: 0,
        price: 35
    },
    {
        picto: 'cycling-bmx-free',
        title: 'Cycling BMX Freestyle',
        description: '',
        datetime: '2024-08-05 10:00:00',
        location: 'Place de la Concorde',
        adressNum: null,
        adressRoad: 'Place de la Concorde',
        city: 'Paris',
        zipCode: 75000,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'cycling-bmx-race',
        title: 'Cycling BMX Racing',
        description: '',
        datetime: '2024-08-05 14:00:00',
        location: 'Place de la Concorde',
        adressNum: null,
        adressRoad: 'Place de la Concorde',
        city: 'Paris',
        zipCode: 75000,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'cycling-mount-bike',
        title: 'Cycling Mountain Bike',
        description: '',
        datetime: '2024-08-08',
        location: 'Pont d\'Iéna - Trocadéro',
        adressNum: null,
        adressRoad: 'Pont d\'Iéna - Trocadéro',
        city: 'Paris',
        zipCode: 75116,
        stocks: 5000,
        sells: 0,
        price: 35
    },
    {
        picto: 'cycling-road',
        title: 'Cycling Road',
        description: '',
        datetime: '2024-08-01 14:00:00',
        location: 'Pont Alexandre III',
        adressNum: null,
        adressRoad: 'Pont Alexandre III',
        city: 'Paris',
        zipCode: 75008,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'cycling-track',
        title: 'Cycling Track',
        description: '',
        datetime: '2024-08-03 10:00:00',
        location: 'Vélodrome National',
        adressNum: 1,
        adressRoad: 'Rue Laurent Fignon, Place de la Paix Celeste',
        city: 'Montigny-le-Bretonneux',
        zipCode: 78180,
        stocks: 2500,
        sells: 0,
        price: 35
    },
    {
        picto: 'diving',
        title: 'Diving', // Plongée-Plongeon
        description: '',
        datetime: '2024-08-12 16:30:00',
        location: 'Centre Aquatique Olympique',
        adressNum: 345,
        adressRoad: 'Avenue du Président Wilson',
        city: 'Saint-Denis',
        zipCode: 93200,
        stocks: 5000,
        sells: 0,
        price: 35
    },
    {
        picto: 'equestrian',
        title: 'Equestrian',
        description: '',
        datetime: '2024-08-05 09:30:00',
        location: 'Château de Versailles',
        adressNum: null,
        adressRoad: 'Place d\'Armes',
        city: 'Versailles',
        zipCode: 78000,
        stocks: 3000,
        sells: 0,
        price: 35
    },
    {
        picto: 'fencing',
        title: 'Fencing', // Escrime
        description: '',
        datetime: '2024-08-18 10:00:00',
        location: 'Grand Palais',
        adressNum: 1 ,
        adressRoad: 'Avenue Wiston Churchill',
        city: 'Paris',
        zipCode: 75008,
        stocks: 15000,
        sells: 0,
        price: 35
    },
    {
        picto: 'football',
        title: 'Football',
        description: '',
        datetime: '2024-07-21 15:00:00',
        location: 'Stade Vélodrome',
        adressNum: 3,
        adressRoad: 'Boulevard Michelet',
        city: 'Marseille',
        zipCode: 13008,
        stocks: 50000,
        sells: 0,
        price: 35
    },
    {
        picto: 'golf',
        title: 'Golf',
        description: '',
        datetime: '2024-07-27 10:00:00',
        location: 'Château de Versailles',
        adressNum: null,
        adressRoad: 'Place d\'Armes',
        city: 'Versailles',
        zipCode: 78000,
        stocks: 3000,
        sells: 0,
        price: 35
    },
    {
        picto: 'handball',
        title: 'Handball',
        description: '',
        datetime: '2025-07-30 15:00:00',
        location: 'Arena Paris Sud (Palais des Expositions - Porte de Versailles)',
        adressNum: 1 ,
        adressRoad: 'Place de la Porte de Versaille',
        city: 'Paris',
        zipCode: 75015,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'hockey',
        title: 'Hockey',
        description: '',
        datetime: '2024-07-30 17:30:00',
        location: 'Arena Champ-de-Mars (Grand Palais éphémère)',
        adressNum: 2,
        adressRoad: 'Place Joffre',
        city: 'Paris',
        zipCode: 72007,
        stocks: 1500,
        sells: 0,
        price: 35
    },
    {
        picto: 'judo',
        title: 'Judo',
        description: '',
        datetime: '2024-07-28 09:30:00',
        location: 'Arena Champ-de-Mars (Grand Palais éphémère)',
        adressNum: 2,
        adressRoad: 'Place Joffre',
        city: 'Paris',
        zipCode: 72007,
        stocks: 1500,
        sells: 0,
        price: 35
    },
    {
        picto: 'marathon-swimming',
        title: 'Marathon Swimming',
        description: '',
        datetime: '2024-07-31 10:00:00',
        location: 'Pont Alexandre III',
        adressNum: null,
        adressRoad: 'Pont Alexandre III',
        city: 'Paris',
        zipCode: 75008,
        stocks: 1500,
        sells: 0,
        price: 35
    },
    {
        picto: 'modern-pentathlon',
        title: 'Modern Pentathlon',
        description: '',
        datetime: '2024-08-01 8:00:00',
        location: 'Pont Alexandre III',
        adressNum: null,
        adressRoad: 'Pont Alexandre III',
        city: 'Paris',
        zipCode: 75008,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'rhytmic-gymnastics',
        title: 'Rhytmic Gymnastics',
        description: '',
        datetime: '2024-08-09 09:30:00',
        location: 'Arena Porte de la Chapelle',
        adressNum: 56,
        adressRoad: 'Boulevard Ney',
        city: 'Paris',
        zipCode: 75018,
        stocks: 10000,
        sells: 0,
        price: 35
    },
    {
        picto: 'rowing',
        title: 'Rowing', //Aviron
        description: '',
        datetime: '2024-08-03 09:30:00',
        location: 'Base nautique de Vaires-sur-Marne',
        adressNum: null,
        adressRoad: 'Route de Torcy',
        city: 'Paris',
        zipCode: 77360,
        stocks: 4000,
        sells: 0,
        price: 35
    },
    {
        picto: 'rugby-sevens',
        title: 'Rugby Sevens',
        description: '',
        datetime: '2024-07-28 18:00:00',
        location: 'Stade de France',
        adressNum: null,
        adressRoad: 'Avenue du Stade de France',
        city: 'Saint-Denis',
        zipCode: 93200,
        stocks: 81000,
        sells: 0,
        price: 35
    },
    {
        picto: 'sailing',
        title: 'Sailing',
        description: '',
        datetime: '2024-08-17 8:30:00',
        location: 'Stade Roland Garros',
        adressNum: null,
        adressRoad: 'Marina',
        city: 'Marseille',
        zipCode: 13000,
        stocks: 25000,
        sells: 0,
        price: 35
    },
    {
        picto: 'shooting',
        title: 'Shooting',
        description: '',
        datetime: '2024-08-03 14:00:00',
        location: 'Place de la Concorde',
        adressNum: null,
        adressRoad: 'Place de la Concorde',
        city: 'Paris',
        zipCode: 75000,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'skateboarding',
        title: 'Skateboarding',
        description: '',
        datetime: '2024-08-01 10:00:00',
        location: 'Place de la Concorde',
        adressNum: null,
        adressRoad: 'Place de la Concorde',
        city: 'Paris',
        zipCode: 75000,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'sport-climbing',
        title: 'Sport Climbing',
        description: '',
        datetime: '2024-08-05 10:00:00',
        location: 'Grand Palais',
        adressNum: 1 ,
        adressRoad: 'Avenue Wiston Churchill',
        city: 'Paris',
        zipCode: 75008,
        stocks: 15000,
        sells: 0,
        price: 35
    },
    {
        picto: 'surfing',
        title: 'Surfing',
        description: '',
        datetime: '2024-08-09',
        location: 'Stade Roland Garros',
        adressNum: null,
        adressRoad: 'Plage de Teahupo\'o',
        city: 'Tahiti',
        zipCode: 98723,
        stocks: 10000,
        sells: 0,
        price: 35
    },
    {
        picto: 'swimming',
        title: 'Swimming',
        description: '',
        datetime: '2024-08-13 10:00:00',
        location: 'Centre Aquatique Olympique',
        adressNum: 345,
        adressRoad: 'Avenue du Président Wilson',
        city: 'Saint-Denis',
        zipCode: 93200,
        stocks: 5000,
        sells: 0,
        price: 35
    },
    {
        picto: 'table-tennis',
        title: 'Table Tennis',
        description: '',
        datetime: '2025-07-26 15:00:00',
        location: 'Arena Paris Sud (Palais des Expositions - Porte de Versailles)',
        adressNum: 1 ,
        adressRoad: 'Place de la Porte de Versaille',
        city: 'Paris',
        zipCode: 75015,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'taekwondo',
        title: 'Taekwondo',
        description: '',
        datetime: '2024-08-21 10:00:00',
        location: 'Grand Palais',
        adressNum: 1 ,
        adressRoad: 'Avenue Wiston Churchill',
        city: 'Paris',
        zipCode: 75008,
        stocks: 15000,
        sells: 0,
        price: 35
    },
    {
        picto: 'tennis',
        title: 'Tennis',
        description: '',
        datetime: '2024-08-11 15:00:00',
        location: 'Stade Roland Garros',
        adressNum: 2,
        adressRoad: 'Avenue Gordon Benett',
        city: 'Paris',
        zipCode: 75016,
        stocks: 5000,
        sells: 0,
        price: 35
    },
    {
        picto: 'trampoline-gymnastics',
        title: 'Trampoline Gymnastics',
        description: '',
        datetime: '2024-08-03 15:30:00',
        location: 'Arena Bercy',
        adressNum: 8,
        adressRoad: 'Boulevard de Bercy',
        city: 'Paris',
        zipCode: 75012,
        stocks: 17000,
        sells: 0,
        price: 35
    },
    {
        picto: 'triathlon',
        title: 'Triathlon',
        description: '',
        datetime: '2024-07-28 10:00:00',
        location: 'Pont Alexandre III',
        adressNum: null,
        adressRoad: 'Pont Alexandre III',
        city: 'Paris',
        zipCode: 75008,
        stocks: 1500,
        sells: 0,
        price: 35
    },
    {
        picto: 'volleyball',
        title: 'Volleyball',
        description: '',
        datetime: '2025-07-26 16:00:00',
        location: 'Arena Paris Sud (Palais des Expositions - Porte de Versailles)',
        adressNum: 1 ,
        adressRoad: 'Place de la Porte de Versaille',
        city: 'Paris',
        zipCode: 75015,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'water-polo',
        title: 'Water Polo',
        description: '',
        datetime: '2024-08-04 15:00:00',
        location: 'Paris La Défense Arena',
        adressNum: 99,
        adressRoad: 'Jardin de l\'Arche',
        city: 'Nanterre',
        zipCode: 92000,
        stocks: 2500,
        sells: 0,
        price: 35
    },
    {
        picto: 'weightlifting',
        title: 'Weightlifting',
        description: '',
        datetime: '2025-07-26 10:00:00',
        location: 'Arena Paris Sud (Palais des Expositions - Porte de Versailles)',
        adressNum: 1 ,
        adressRoad: 'Place de la Porte de Versaille',
        city: 'Paris',
        zipCode: 75015,
        stocks: 2000,
        sells: 0,
        price: 35
    },
    {
        picto: 'wrestling',
        title: 'Wrestling', //lutte
        description: '',
        datetime: '2024-08-15 09:30:00',
        location: 'Arena Champ-de-Mars (Grand Palais éphémère)',
        adressNum: 2,
        adressRoad: 'Place Joffre',
        city: 'Paris',
        zipCode: 75007,
        stocks: 1500,
        sells: 0,
        price: 35
    },
];

const offers = [
    {
        title: 'Solo',
        description: 'Vous souhaitez réserver des e-tickets pour UNE seule personne à l\'occasion de vos événements sportfif favoris ? Voici l\'offre Solo pour profitez des Jeux Olympiques Paris 2024 en toute tranquilité.',
        ticketsQty: 1,
        promo: 0,
    },
    {
        title: 'Duo',
        description: 'Avec un.e ami.e, un.e collègue, en couple ou avec un.e membre de votre famille, choississez l\'offre Duo pour regrouper vos e-tickets et vos paiement en une seule fois.',
        ticketsQty: 2,
        promo: 0,
    },
    {
        title: 'Family',
        description: 'Le sport ça se vie en famille ! Choisissez l\'offre Family pour regrouper vos places et vos achats en un seul e-ticket par événement sportif. Assister aux Jeux Olympiques Paris 2024 l\'esprit tranquille.',
        ticketsQty: 4,
        promo: 0,
    },
];

export { users, events, offers };
